### ISSUE TITLE
organizationName limited to 64 octets

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#183]
Continuing discussion from https://github.com/letsencrypt/acme-spec/commit/64fbfde2375145c635ceb47ccae5329c5797f192#commitcomment-12025076...

According to [RFC5280](http://tools.ietf.org/html/rfc5280), `organizationName` is limited to 64 octets (`ub-organization-name-length INTEGER ::= 64`). This is too small to carry JWS signature field in DVSNI challenge response.

Indeed, this is limited in practice:
```python
import json

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
import OpenSSL

from acme import jose

private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
    backend=default_backend()
)

jwk = jose.JWKRSA(key=jose.ComparableRSAKey(private_key))
jws = jose.JWS.sign(payload="{}", key=jwk, alg=jose.RS256)
signature = jws.signature._fields["signature"].encode(jws.signature.signature)
print len(signature)
cert = OpenSSL.crypto.X509()
cert.get_subject().O = signature
```

```
$ python spec-dvsni-organization-bug.py 
342
Traceback (most recent call last):
  File "spec-dvsni-organization-bug.py", line 20, in <module>
    cert.get_subject().O = signature
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 469, in __setattr__
    _raise_current_error()
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]
```

**Comment by martinthomson** [comment]
Why does this need to fit in an existing field?  A new (non-critical) extension can be any length.

**Comment by jdkasten** [comment]
In the first implementation of DVSNI, we used a new extension. However, there isn't much library support for setting custom OID extensions.  In the interest of client compatibility, we attempted to override existing fields.
